services:
  db:
    image: postgres:latest
    container_name: fastapi-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_auth
    ports:
      - "5432:5432"
    volumes:
      - fastapi-auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  mongodb:
    image: mongo:latest
    container_name: fastapi-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - fastapi-mongo-db-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: fastapi-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - fastapi-qdrant-data:/qdrant/storage
  
  web:
    build: .
    container_name: fastapi-auth-app
    # The command is now handled by the entrypoint script in the Dockerfile
    volumes:
      - .:/app
      - ml_models:/root/.cache/huggingface 
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      qdrant:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fastapi_auth
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=social_media
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET=your-jwt-secret-here
      - MAIL_USERNAME=your-email-username
      - MAIL_PASSWORD=your-email-password
      - MAIL_FROM=your-email-address
      - MAIL_PORT=5432
      - MAIL_SERVER=localhost
      - MAIL_STARTTLS=false
      - MAIL_SSL_TLS=false

volumes:
  fastapi-auth-db-data:
    name: fastapi-auth-db-data
  fastapi-mongo-db-data:
    name: fastapi-mongo-db-data
  fastapi-qdrant-data:
    name: fastapi-qdrant-data
  ml_models:
