# app/posts/router.py
from fastapi import APIRouter
from .routers.classification import router as classification_router
from .routers.core import router as posts_core_router
from .routers.search import router as search_router
from .routers.threads import router as threads_router
from .routers.user_content import router as user_content_router
from .routers.engagement import router as engagement_router

# Create posts router
router = APIRouter()

# Include all posts-related routers
router.include_router(posts_core_router)            # Will be at /api/v1/posts/...
router.include_router(classification_router)         # Will be at /api/v1/posts/content/...
router.include_router(search_router)                # Will be at /api/v1/posts/search/...
router.include_router(threads_router)               # Will be at /api/v1/posts/threads/...
router.include_router(user_content_router)          # Will be at /api/v1/posts/users/...
router.include_router(engagement_router)            # Will be at /api/v1/posts/engagement/...