"""migrations-fix-circular-deps3

Revision ID: 362f4f42e43f
Revises: d78cb2179cb8
Create Date: 2024-12-11 06:38:53.160929+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362f4f42e43f'
down_revision: Union[str, None] = 'd78cb2179cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
