"""migrations-fix-circular-deps5

Revision ID: 3fc0dd8124bd
Revises: a243456f4f24
Create Date: 2024-12-11 06:56:25.070100+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc0dd8124bd'
down_revision: Union[str, None] = 'a243456f4f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
