"""migrations-fix-created-thread-error

Revision ID: 7f14d5149d2f
Revises: 94dcfea6812f
Create Date: 2024-12-11 06:28:31.149800+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f14d5149d2f'
down_revision: Union[str, None] = '94dcfea6812f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
