"""migrations-fix-circular-deps4

Revision ID: a243456f4f24
Revises: 362f4f42e43f
Create Date: 2024-12-11 06:51:24.455823+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a243456f4f24'
down_revision: Union[str, None] = '362f4f42e43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
